decoder:
  deterministicOnSeg: False
  nlabels: 1
  n_locallabels: 10
z_dist:
  type: uniform
  dim: 5
encoder:
  nlabels: 1
  n_locallabels: 10
  kwargs:
    deeper_arch: False
discriminator:
  nlabels: 1
  n_locallabels: 10
label_generator:
  zdim: 50
  label_size: 16
  nlabels: 1
  n_locallabels: 10
  conditioning: unconditional
  kwargs:
    deeper_arch: True
inherit_from: configs/imagenet100/default.yaml
training:
  out_dir: output/imagenet100/selfcondgan_labelRes16_modArchi_DCGANDisc_deeperarchLG_K_10_ZImg5_ZLab50
  reg_param: 0.1
  con_loss: True
  lambda_LabConLoss: 0.1
