decoder:
  deterministicOnSeg: False
  nlabels: 1
  n_locallabels: 25
z_dist:
  type: uniform
  dim: 10
encoder:
  nlabels: 1
  n_locallabels: 25
  kwargs:
    deeper_arch: False
    classifier_mod: False
discriminator:
  nlabels: 1
  n_locallabels: 25
  kwargs:
    noSegPath: 0
label_generator:
  zdim: 50
  label_size: 16
  nlabels: 1
  n_locallabels: 25
  conditioning: unconditional
  kwargs:
    deeper_arch: True
inherit_from: configs/imagenet100/default.yaml
training:
  out_dir: output/imagenet100/selfcondgan_labelRes16_DCGANDisc_deeperarchLG_K_25_ZImg10_ZLab50_lrdecay
  reg_param: 0.1
  con_loss: True
  lambda_LabConLoss: 0.1
  entropy_loss: False
