decoder:
  deterministicOnSeg: False
  nlabels: 1
  n_locallabels: 5
z_dist:
  type: uniform
  dim: 5
encoder:
  nlabels: 1
  n_locallabels: 5
  kwargs:
    deeper_arch: True
    classifier_mod: False
discriminator:
  nlabels: 1
  n_locallabels: 5
  kwargs:
    noSegPath: 0
label_generator:
  zdim: 30
  label_size: 32
  nlabels: 1
  n_locallabels: 5
  conditioning: unconditional
  kwargs:
    deeper_arch: True
inherit_from: configs/lsun256/default.yaml
training:
  out_dir: output/lsun256/selfcondgan_labelRes32_K_5_ZImg5_ZLab30
  reg_type: real
  reg_param: 10.
  con_loss: True
  lambda_LabConLoss: 0.1
  entropy_loss: False
