decoder:
  deterministicOnSeg: False
encoder:
  kwargs:
    deeper_arch: False
    classifier_mod: False
discriminator:
  kwargs:
    noSegPath: 3
label_generator:
  zdim: 30
  label_size: 16
  n_locallabels: 20
  kwargs:
    deeper_arch: False
inherit_from: configs/lsun_bedroom/default.yaml
training:
  out_dir: output/lsun_bedroom/selfcondgan_labelRes16_K_20_ZImg10_ZLab30_var3_ema_smallLG
  reg_param: 0.1
  con_loss: True
  lambda_LabConLoss: 0.1
  entropy_loss: False
  take_model_average: True

