data:
  type: cifar10
  train_dir: data/CIFAR
  img_size: 32
  nlabels: 10
decoder:
  name: cifar_bigan
  zdim: 5
encoder:
  name: cifar_bigan
label_generator:
  label_size: 8
  name: cifar_bigan
  zdim: 30
discriminator:
  name: cifar_bigan
qhead_discriminator:
  name: cifar_bigan
z_dist:
  type: uniform
training:
  gan_type: standard
  reg_type: none
  reg_param: 0.
  take_model_average: false
  sample_nlabels: 20
  log_every: 1000
  inception_every: 10000
  batch_size: 64