decoder:
  name: dcgan_deep_onlylocal_clust
  deterministicOnSeg: True
  nlabels: 1
  n_locallabels: 2
encoder:
  name: dcgan_deep_onlylocal_clust
  nlabels: 1
  n_locallabels: 2
discriminator:
  name: dcgan_deep_onlylocal_clust_bigan
  kwargs:
    qhead_withImg: True
  nlabels: 1
  n_locallabels: 2
label_generator:
  label_size: 8
  name: dcgan_label_gen
  nlabels: 1
  n_locallabels: 2
  conditioning: unconditional
label_discriminator:
  label_size: 8
  name: dcgan_label_gen
  nlabels: 1
  n_locallabels: 2
  conditioning: unconditional
inherit_from: configs/cifar/default.yaml
training:
  out_dir: output/cifar/K2_2_withDisc_BiGAN_detOnSeg_CONLOSSIMG_ImgSeg_2classes
  use_disc: True
  con_loss: True