decoder:
  deterministicOnSeg: True
  nlabels: 1
  n_locallabels: 20
encoder:
  nlabels: 1
  n_locallabels: 20
discriminator:
  nlabels: 1
  n_locallabels: 20
label_generator:
  label_size: 32
  nlabels: 1
  n_locallabels: 20
  conditioning: unconditional
inherit_from: configs/places/default.yaml
training:
  out_dir: output/places/selfcondgan_labelRes32_K2_20
  reg_param: 0.1
  con_loss: True