decoder:
  deterministicOnSeg: False
  nlabels: 1
  n_locallabels: 5
z_dist:
  type: uniform
  dim: 5
encoder:
  nlabels: 1
  n_locallabels: 5
  kwargs:
    deeper_arch: False
    classifier_mod: False
discriminator:
  nlabels: 1
  n_locallabels: 5
  kwargs:
    noSegPath: True
label_generator:
  zdim: 30
  label_size: 16
  nlabels: 1
  n_locallabels: 5
  conditioning: unconditional
  kwargs:
    deeper_arch: True
inherit_from: configs/lsun/default.yaml
training:
  out_dir: output/lsun/selfcondgan_labelRes16_modArchi_DCGANDisc_deeperarchLG_K_5_ZImg5_ZLab30_DifArchiDisc
  reg_param: 0.1
  con_loss: True
  lambda_LabConLoss: 0.1
  entropy_loss: False
