decoder:
  deterministicOnSeg: False
  nlabels: 1
  n_locallabels: 15
z_dist:
  type: uniform
  dim: 5
encoder:
  nlabels: 1
  n_locallabels: 15
  kwargs:
    deeper_arch: False
discriminator:
  nlabels: 1
  n_locallabels: 15
label_generator:
  zdim: 50
  label_size: 16
  nlabels: 1
  n_locallabels: 15
  conditioning: unconditional
  kwargs:
    deeper_arch: False
inherit_from: configs/lsun/default.yaml
training:
  out_dir: output/lsun/selfcondgan_labelRes16_modArchi_DCGANDisc_deeperarch_K_15_lambda0.1_ZImg10_ZLab50
  reg_param: 0.1
  con_loss: True
  lambda_LabConLoss: 0.1
