decoder:
  deterministicOnSeg: False
  nlabels: 1
  n_locallabels: 20
z_dist:
  type: uniform
  dim: 10
encoder:
  nlabels: 1
  n_locallabels: 20
  kwargs:
    deeper_arch: True
discriminator:
  nlabels: 1
  n_locallabels: 20

label_generator:
  label_size: 16
  nlabels: 1
  n_locallabels: 20
  conditioning: unconditional
  kwargs:
    deeper_arch: True
inherit_from: configs/lsun/default.yaml
training:
  out_dir: output/lsun/selfcondgan_labelRes16_modArchi_DCGANDisc_deeperarch_K_20_lambda0.1_ZImg10
  reg_param: 0.1
  con_loss: True
  lambda_LabConLoss: 0.1
